name: package

on:
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            -   name: Setup AWS CLI
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0.2-release/ubuntu2404/swift-6.0.2-RELEASE"
                    swift-id: "swift-6.0.2-RELEASE-ubuntu24.04"

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build products
                env:
                    IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
                run: Scripts/Package

            -   name: Test firewall
                run: swift run -c release FirewallUsage 98.223.208.128

            -   name: Upload firewall
                run: aws s3 cp firewall.bson.gz s3://swiftinit/ip/firewall.bson.gz
